#+TITLE: 2024年11月份

* 20241108
找一个地方记录一些思考过的内容，也没有什么目的和用意。

但行好事，莫问前程。

阅读原著和经典，不要读解读性或评论性的内容。

戒掉咖啡因，这是一个决定。

洗冷水澡，从明天开始。

最了不起的超能力，是改变自我的能力。

要从生活中获得回报，你需要做的并不是合群，而是从人群中脱颖而出。

今天，做到了戒掉咖啡因这件事情。

勇气不是在枪林弹雨中冲锋陷阵，而是不在乎别人怎么想。

智慧是一种知道个人行为的长期后果的思维能力。

阅读不是为了自我提升，而是出于好奇心和兴趣。

* 20241109
如果没有把时间花在想做的事情上，既没有赚到钱，也没有学到东西，你就要问问自己到底在瞎忙什么。

今天开始，洗冷水澡。

今天开始，戒掉咖啡因。

能改变自己，就是神。想改变别人，就是神经病。

厂家卖货的思维：产品好应该卖得好。
消费者买货的思维：卖得好所以产品好。

自尊心特别强的人，大多数都是弱者。
强者才会示弱，而弱者只会逞强。

内心无比促弱，嘴上无比刚强--输家的画像。

* 20241110
熵，无情而永恒，慢慢的解构我周围的一切。

* 20241111
洗冷水澡和戒咖啡，今天做到了。

先胜而后求战。

胜负在于潜在客户的心智。

* 20241112
此时此刻，我的内心是无比复杂了。在这个动荡的深秋，充满了焦虑和不安。

学习一门新语言，就像打开了一扇通往新世界的大门。

干事比想事容易很多。

* 20241113
动起来，才更有机会。

开卷有益，开卷有益，开卷有益。

物理学的魅力被概念和方程式抹杀了。

自由的认清自己的激情，毫不妥协、无怨无悔地活出激情。

喝点酒，可以调节状态，不管是往好的方面还是坏的方面，它是有作用的。

进化极致追求节省体力和脑力，导致生物只对极端的环境压力做出反应，要么适应，要么灭绝。

* 20241114
生活的简单时刻值得细细品味。

在数量级上的提升，才是正路。

社会的关键资源，不再是资本，而是知识。

* 20241115
早上冷水洗澡的感觉越来越好了。

科学的诀窍是跟随者你的领域一起成长。不要太超前。

请不要急于完成，要享受过程。

* 20241116
随身背个包，装两本书，把等待的时间都编成享受的时间，也是件美好的事情。

对于数据分析这项工作的价值，越来越有兴趣。

熟悉一些脚手架工具是很必要的，比如：Polars，Burn

* 20241117
牺牲睡眠时间去干一些成瘾性事情，是最蠢的行为。

* 20241118
个体的尊严是至高无上的。

时代不断加速发展，每个人的注意力都集中在了更热门的信息来源上，而传统文献却一直被忽视。

* 20241119
专用设备，会引发更加专注还是形式注意，不得而知，尝试一下。

一旦我们确定了居住，工作和上学的准确地点，
我们大体上也就决定了哪些人将会成为我们生命中最重要的人。

不着急，不害怕，不要脸。

不要试图改变人们的心智。

* 20241120
平衡理论：人们预期他们的思想、感情和社会关系能够保持一致。

成为小池塘里的大鱼，然后扩大池塘，总好过成为大池塘里的小鱼。

* 20241121
“第一印象”有很大的利用价值，它会把人们的注意力导向某类新信息，
影响后来获得的新事实的解释，
导致人们不能客观公平、不偏不倚地处理来自他人的信息。
